name: Publish Package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  setup:
    name: Checkout Code & Setup Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10.14'

  extract_version:
    name: Extract Version from Tag
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extract Version from Tag
        id: extract_version
        run: |
          echo "Extracting version from tag..."
          # Extract version number from the tag
          tag=${GITHUB_REF##*/}
          version=${tag#v}
          if [[ ! $version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid tag format. Expected 'vX.Y.Z'"
            exit 1
          fi
          echo "version=$version" >> $GITHUB_ENV

  build_and_publish:
    name: Build Package & Publish to PyPI
    needs: [setup, extract_version]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Update version
        run: |
          echo "Bumping version to ${{ env.version }}..."
          python scripts/bump_version.py ${{ env.version }}
      - name: Build package
        run: |
          python setup.py sdist bdist_wheel
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload dist/*
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pyparsec-artifacts
          path: dist/*
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
